PLAN = {
    "Day 1": "Pick your wake-up time right now and stick to it every day.",
    "Day 2": "Anchor your wake-up time with morning light.",
    "Day 3": "Observe morning light, even if it's a bit cloudy.",
    "Day 4": "Keep wake-up time consistent to see sleep improvements.",
    "Day 5": "Ensure consistency in your wake-up schedule.",
    "Day 6": "Test your consistency with a weekend wake-up test.",
    "Day 7": "Maintain the same wake-up time on Sundays.",
    "Day 8": "Calculate your afternoon caffeine cutoff time.",
    "Day 9": "Commit to your new caffeine cutoff time.",
    "Day 10": "Skip the second cup of coffee today.",
    "Day 11": "Notice any afternoon caffeine withdrawal.",
    "Day 12": "Follow your daily caffeine cutoff strictly.",
    "Day 13": "Ensure consistency in your daily caffeine avoidance.",
    "Day 14": "Assess how cutting off caffeine affects your evenings.",
    "Day 15": "Crack a window in your bedroom to keep it cool.",
    "Day 16": "Ensure your room is pitch dark before sleeping.",
    "Day 17": "Move your phone charger across the room.",
    "Day 18": "Make sure your bed is used only for sleep.",
    "Day 19": "Keep your bedroom cool and dark tonight.",
    "Day 20": "Add background noise like a fan or white noise app.",
    "Day 21": "Ensure your sleep environment is completely set up.",
    "Day 22": "Write down 2-3 specific if-then plans for your evening.",
    "Day 23": "Execute your if-then plan for winding down tonight.",
    "Day 24": "Dim your room lights early to prepare for sleep.",
    "Day 25": "Avoid all screens at least 2-3 hours before bed.",
    "Day 26": "Stick to your wind-down routine tonight.",
    "Day 27": "Maintain your wind-down routine even on a busy day.",
    "Day 28": "Ensure no screens are used before bedtime.",
    "Day 29": "Consolidate: run the full stack of habits again.",
    "Day 30": "Write down which single habit made the biggest difference."
}